/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as TimesheetApprovalTokenRouteImport } from './routes/timesheet-approval.$token'
import { Route as ReferenceTokenRouteImport } from './routes/reference.$token'
import { Route as ApplyRefRouteImport } from './routes/apply.$ref'
import { Route as AuthenticatedTimesheetsRouteImport } from './routes/_authenticated/timesheets'
import { Route as AuthenticatedTempsRouteImport } from './routes/_authenticated/temps'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSammieRouteImport } from './routes/_authenticated/sammie'
import { Route as AuthenticatedPlacementsRouteImport } from './routes/_authenticated/placements'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedTimesheetsIndexRouteImport } from './routes/_authenticated/timesheets.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedTimesheetsIdRouteImport } from './routes/_authenticated/timesheets.$id'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedComplianceIdRouteImport } from './routes/_authenticated/compliance.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedCandidatesNewRouteImport } from './routes/_authenticated/candidates.new'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TimesheetApprovalTokenRoute = TimesheetApprovalTokenRouteImport.update({
  id: '/timesheet-approval/$token',
  path: '/timesheet-approval/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceTokenRoute = ReferenceTokenRouteImport.update({
  id: '/reference/$token',
  path: '/reference/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRefRoute = ApplyRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => ApplyRoute,
} as any)
const AuthenticatedTimesheetsRoute = AuthenticatedTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTempsRoute = AuthenticatedTempsRouteImport.update({
  id: '/temps',
  path: '/temps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSammieRoute = AuthenticatedSammieRouteImport.update({
  id: '/sammie',
  path: '/sammie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementsRoute = AuthenticatedPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimesheetsIndexRoute =
  AuthenticatedTimesheetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTimesheetsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)
const AuthenticatedTimesheetsIdRoute =
  AuthenticatedTimesheetsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTimesheetsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedComplianceIdRoute =
  AuthenticatedComplianceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedComplianceRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedCandidatesNewRoute =
  AuthenticatedCandidatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/compliance': typeof AuthenticatedComplianceRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/map': typeof AuthenticatedMapRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/sammie': typeof AuthenticatedSammieRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/temps': typeof AuthenticatedTempsRoute
  '/timesheets': typeof AuthenticatedTimesheetsRouteWithChildren
  '/apply/$ref': typeof ApplyRefRoute
  '/reference/$token': typeof ReferenceTokenRoute
  '/timesheet-approval/$token': typeof TimesheetApprovalTokenRoute
  '/apply/': typeof ApplyIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/compliance/$id': typeof AuthenticatedComplianceIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/timesheets/$id': typeof AuthenticatedTimesheetsIdRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/timesheets/': typeof AuthenticatedTimesheetsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/map': typeof AuthenticatedMapRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/sammie': typeof AuthenticatedSammieRoute
  '/temps': typeof AuthenticatedTempsRoute
  '/apply/$ref': typeof ApplyRefRoute
  '/reference/$token': typeof ReferenceTokenRoute
  '/timesheet-approval/$token': typeof TimesheetApprovalTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/compliance/$id': typeof AuthenticatedComplianceIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/timesheets/$id': typeof AuthenticatedTimesheetsIdRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/timesheets': typeof AuthenticatedTimesheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/compliance': typeof AuthenticatedComplianceRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/placements': typeof AuthenticatedPlacementsRoute
  '/_authenticated/sammie': typeof AuthenticatedSammieRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/temps': typeof AuthenticatedTempsRoute
  '/_authenticated/timesheets': typeof AuthenticatedTimesheetsRouteWithChildren
  '/apply/$ref': typeof ApplyRefRoute
  '/reference/$token': typeof ReferenceTokenRoute
  '/timesheet-approval/$token': typeof TimesheetApprovalTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/compliance/$id': typeof AuthenticatedComplianceIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/timesheets/$id': typeof AuthenticatedTimesheetsIdRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/timesheets/': typeof AuthenticatedTimesheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/account'
    | '/applications'
    | '/bookings'
    | '/candidates'
    | '/clients'
    | '/compliance'
    | '/inbox'
    | '/interviews'
    | '/jobs'
    | '/map'
    | '/placements'
    | '/sammie'
    | '/settings'
    | '/temps'
    | '/timesheets'
    | '/apply/$ref'
    | '/reference/$token'
    | '/timesheet-approval/$token'
    | '/apply/'
    | '/bookings/$id'
    | '/candidates/$id'
    | '/candidates/new'
    | '/clients/$id'
    | '/compliance/$id'
    | '/jobs/$id'
    | '/settings/company'
    | '/settings/team'
    | '/timesheets/$id'
    | '/bookings/'
    | '/candidates/'
    | '/clients/'
    | '/compliance/'
    | '/jobs/'
    | '/settings/'
    | '/timesheets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/account'
    | '/applications'
    | '/inbox'
    | '/interviews'
    | '/map'
    | '/placements'
    | '/sammie'
    | '/temps'
    | '/apply/$ref'
    | '/reference/$token'
    | '/timesheet-approval/$token'
    | '/'
    | '/apply'
    | '/bookings/$id'
    | '/candidates/$id'
    | '/candidates/new'
    | '/clients/$id'
    | '/compliance/$id'
    | '/jobs/$id'
    | '/settings/company'
    | '/settings/team'
    | '/timesheets/$id'
    | '/bookings'
    | '/candidates'
    | '/clients'
    | '/compliance'
    | '/jobs'
    | '/settings'
    | '/timesheets'
  id:
    | '__root__'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/applications'
    | '/_authenticated/bookings'
    | '/_authenticated/candidates'
    | '/_authenticated/clients'
    | '/_authenticated/compliance'
    | '/_authenticated/inbox'
    | '/_authenticated/interviews'
    | '/_authenticated/jobs'
    | '/_authenticated/map'
    | '/_authenticated/placements'
    | '/_authenticated/sammie'
    | '/_authenticated/settings'
    | '/_authenticated/temps'
    | '/_authenticated/timesheets'
    | '/apply/$ref'
    | '/reference/$token'
    | '/timesheet-approval/$token'
    | '/_authenticated/'
    | '/apply/'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/candidates/new'
    | '/_authenticated/clients/$id'
    | '/_authenticated/compliance/$id'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/team'
    | '/_authenticated/timesheets/$id'
    | '/_authenticated/bookings/'
    | '/_authenticated/candidates/'
    | '/_authenticated/clients/'
    | '/_authenticated/compliance/'
    | '/_authenticated/jobs/'
    | '/_authenticated/settings/'
    | '/_authenticated/timesheets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReferenceTokenRoute: typeof ReferenceTokenRoute
  TimesheetApprovalTokenRoute: typeof TimesheetApprovalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/timesheet-approval/$token': {
      id: '/timesheet-approval/$token'
      path: '/timesheet-approval/$token'
      fullPath: '/timesheet-approval/$token'
      preLoaderRoute: typeof TimesheetApprovalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/$token': {
      id: '/reference/$token'
      path: '/reference/$token'
      fullPath: '/reference/$token'
      preLoaderRoute: typeof ReferenceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$ref': {
      id: '/apply/$ref'
      path: '/$ref'
      fullPath: '/apply/$ref'
      preLoaderRoute: typeof ApplyRefRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/_authenticated/timesheets': {
      id: '/_authenticated/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof AuthenticatedTimesheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/temps': {
      id: '/_authenticated/temps'
      path: '/temps'
      fullPath: '/temps'
      preLoaderRoute: typeof AuthenticatedTempsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sammie': {
      id: '/_authenticated/sammie'
      path: '/sammie'
      fullPath: '/sammie'
      preLoaderRoute: typeof AuthenticatedSammieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placements': {
      id: '/_authenticated/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof AuthenticatedPlacementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timesheets/': {
      id: '/_authenticated/timesheets/'
      path: '/'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof AuthenticatedTimesheetsIndexRouteImport
      parentRoute: typeof AuthenticatedTimesheetsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/_authenticated/timesheets/$id': {
      id: '/_authenticated/timesheets/$id'
      path: '/$id'
      fullPath: '/timesheets/$id'
      preLoaderRoute: typeof AuthenticatedTimesheetsIdRouteImport
      parentRoute: typeof AuthenticatedTimesheetsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/compliance/$id': {
      id: '/_authenticated/compliance/$id'
      path: '/$id'
      fullPath: '/compliance/$id'
      preLoaderRoute: typeof AuthenticatedComplianceIdRouteImport
      parentRoute: typeof AuthenticatedComplianceRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/candidates/new': {
      id: '/_authenticated/candidates/new'
      path: '/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof AuthenticatedCandidatesNewRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedCandidatesRouteChildren {
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedCandidatesNewRoute: typeof AuthenticatedCandidatesNewRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
}

const AuthenticatedCandidatesRouteChildren: AuthenticatedCandidatesRouteChildren =
  {
    AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
    AuthenticatedCandidatesNewRoute: AuthenticatedCandidatesNewRoute,
    AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  }

const AuthenticatedCandidatesRouteWithChildren =
  AuthenticatedCandidatesRoute._addFileChildren(
    AuthenticatedCandidatesRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedComplianceRouteChildren {
  AuthenticatedComplianceIdRoute: typeof AuthenticatedComplianceIdRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
}

const AuthenticatedComplianceRouteChildren: AuthenticatedComplianceRouteChildren =
  {
    AuthenticatedComplianceIdRoute: AuthenticatedComplianceIdRoute,
    AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  }

const AuthenticatedComplianceRouteWithChildren =
  AuthenticatedComplianceRoute._addFileChildren(
    AuthenticatedComplianceRouteChildren,
  )

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTimesheetsRouteChildren {
  AuthenticatedTimesheetsIdRoute: typeof AuthenticatedTimesheetsIdRoute
  AuthenticatedTimesheetsIndexRoute: typeof AuthenticatedTimesheetsIndexRoute
}

const AuthenticatedTimesheetsRouteChildren: AuthenticatedTimesheetsRouteChildren =
  {
    AuthenticatedTimesheetsIdRoute: AuthenticatedTimesheetsIdRoute,
    AuthenticatedTimesheetsIndexRoute: AuthenticatedTimesheetsIndexRoute,
  }

const AuthenticatedTimesheetsRouteWithChildren =
  AuthenticatedTimesheetsRoute._addFileChildren(
    AuthenticatedTimesheetsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRouteWithChildren
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedPlacementsRoute: typeof AuthenticatedPlacementsRoute
  AuthenticatedSammieRoute: typeof AuthenticatedSammieRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTempsRoute: typeof AuthenticatedTempsRoute
  AuthenticatedTimesheetsRoute: typeof AuthenticatedTimesheetsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRouteWithChildren,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedPlacementsRoute: AuthenticatedPlacementsRoute,
  AuthenticatedSammieRoute: AuthenticatedSammieRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTempsRoute: AuthenticatedTempsRoute,
  AuthenticatedTimesheetsRoute: AuthenticatedTimesheetsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApplyRouteChildren {
  ApplyRefRoute: typeof ApplyRefRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyRefRoute: ApplyRefRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
  AuthRoute: AuthRoute,
  ReferenceTokenRoute: ReferenceTokenRoute,
  TimesheetApprovalTokenRoute: TimesheetApprovalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
