// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltpsljknjenpomsxixlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0cHNsamtuamVucG9tc3hpeGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4NTM3NTcsImV4cCI6MjA5ODQyOTc1N30.Xi_7L5Cf5ZrxJomiqXB2Kj1SC6Ia90PvKY4wrVYJOeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});